[package]
name = "tc-state"
version = "0.1.0"
edition = "2021"

[dependencies]
async-hash = { path = "../deps/async-hash", version = "0.6" }
bytes = "1"
destream = { path = "../deps/destream", version = "0.10" }
futures = "0.3"
hex = "0.4"
number-general = { path = "../deps/number-general", version = "0.14", default-features = false, features = ["stream"] }
pathlink = { path = "../deps/pathlink", features = ["hash"] }
safecast = "0.2"
tc-ir = { path = "../tc-ir" }
tc-collection = { path = "../tc-collection" }
tc-error = { path = "../tc-error" }
tc-value = { path = "../tc-value" }

[dev-dependencies]
destream_json = { path = "../deps/destream_json" }
freqfs = { path = "../deps/freqfs", version = "0.13" }
tokio = { version = "1", features = ["rt-multi-thread", "time", "sync", "fs", "macros"] }
umask = "2.1"
